FROM ruby:2.3.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /CSR
WORKDIR /CSR
ADD Gemfile /CSR/Gemfile
ADD Gemfile.lock /CSR/Gemfile.lock
RUN bundle install
ADD . /CSR
